### ISSUE TITLE
[Anon] Bug report: Wood Elves - 8thBRB_8thAB.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/whfb#167] opened 2015-03-18 21:36 UTC
**File:** Wood Elves - 8thBRB_8thAB.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** Wood elf war dancers come up in the roster view with no stats of any sort. I.e. no stat line, no weapons, equipment or special rules. 
Either these are missing from the data files or they are not being properly imported.
Hope you can fix the big.

**Comment by Kithan87** [comment] 2020-02-23 23:20
Unable to reproduce in v8.8.0 v15.  Closing issue as wood elf war dancers correctly show up with the profiles as expected.

**Closed by Kithan87** 2020-02-23 23:20 UTC
Labels: unable to replicate
