### ISSUE TITLE
[Anon] Bug report: Wood Elves - 8thBRB_8thAB.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/whfb#21] opened 2014-05-12 14:47 UTC
Glade Guard, Deepwood Scouts, and Glade Riders don't have there options to buy Enchanted Arrows or there 25 point allowance to buy a magic Standard.

**Comment by taalas** [comment] 2015-07-02 06:45
I know this issue is quite old but I can only reproduce this for a small part of what you reported:

Example:
- Adding a Glade Guard will create a Glade Guard group and 10 Glade Guard instances, choosing the 10x Glade Guard entry will allow selection of magic arrows for the whole unit.
- Selecting the standard bearer option and then clicking the new Standard Bearer entry will allow selection of the magic standard.

The only problem I can reproduce is for the Deepwood Scouts standard bearer.

**Comment by taalas** [comment] 2015-07-02 06:47
To follow up on this: after re-checking the AB the Deepwood Scout standard bearer may not choose a magic standard, so this entry is correct as well.

I am closing this for now since there doesn't seem to be an issue with this (or not any more).

**Closed by taalas** 2015-07-02 06:47 UTC
Labels: bug
