### ISSUE TITLE
[Anon] Bug report: Warhammer Fantasy 8th ed.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/whfb#177] opened 2015-05-05 10:08 UTC
**File:** Warhammer Fantasy 8th ed.gstz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** The Talisman of Protection (10 Points) which is listed under magic items /talismans should be corrected to 15 points.

**Comment by GreetingsGQ** [comment] 2015-05-31 20:10
Duplicate of #175

**Closed** 2015-05-31 20:10 UTC
