### ISSUE TITLE
[Anon] Bug report: Wood Elves - 8thBRB_8thAB.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/whfb#198] opened 2015-11-25 14:19 UTC
**File:** Wood Elves - 8thBRB_8thAB.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** Yes

**Description:** When I have multiple Glade Captains in my list, I cannot select their magic arrows individually. e.g. I cannot give the first one 'Arcane Bodkins' and the second 'Hagbane Tips'. Every time I change the selection for one of them all the other ones are changed as well.

**Comment by Kithan87** [comment] 2020-02-23 23:21
Duplicate of #22 Closing as its already been resolved.

**Closed by Kithan87** 2020-02-23 23:21 UTC
