### ISSUE TITLE
[Anon] Bug report: Dark Elves - 8thBRB_8thAB.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/whfb#182] opened 2015-06-08 22:29 UTC
**File:** Dark Elves - 8thBRB_8thAB.catz

**BattleScribe version:** 1.15.06

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Hi there, excellent catalogue so thanks.

When giving a level 4 sorceress the Black Amulet (Talisman), it gives the red exclamation mark and says 'Magic Items has spent 10pts too much on Talismans (maximum 50pts)'. I don't believe there actually is a maximum though. Her magic item allowance is 100pts.

Thanks,

James (jjwroot@gmail.com)

**Comment by DurzoBlintDeluxe** [comment] 2019-10-15 08:29
Seems to be fixed already. May be closed.

**Comment by Kithan87** [comment] 2020-02-22 16:41
Not reproducible in v75 of Dark Elves file.  Closing as not reproducible.

**Closed by Kithan87** 2020-02-22 16:41 UTC
Labels: unable to replicate
