### ISSUE TITLE
[Anon] Bug report: Beastmen - 8thBRB_7thAB.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/whfb#220] opened 2017-02-19 17:10 UTC
**File:** Beastmen - 8thBRB_7thAB.catz

**BattleScribe version:** 2.11.66

**Platform:** Windows

**Dropbox:** No

**Description:** For Beastmen armylists: validation error. It is asking for a Tuskor and razorgor chariot to be included as mandatory in troops and special. Which is incorrect. However even when you add these in it still reports errors. Should be easy to fix

**Comment by Kithan87** [comment] 2020-02-24 17:51
I am not able to reproduce this issue anymore.  Adding in a number of units doesn't seem to force this validation error to show up.  Tried it out on both standard and End Times without seeing this come up.  Closing as not reproducible v3 of the file, BS 2.03.12

**Closed by Kithan87** 2020-02-24 17:51 UTC
Labels: unable to replicate
