### ISSUE TITLE
[Anon] Bug report: Undead Legions_2014.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/whfb#173] opened 2015-04-03 17:13 UTC
**File:** Undead Legions_2014.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** The Tomb Kings lord High Queen Khalida is listen in the Undead Legions book as a character that can be used in Undesd Legions armies, but is not listed in battlescribe as an option for Undead Legions. I have checked on Mac and andriod

**Comment by Kithan87** [comment] 2020-03-23 23:28
Duplicate of #109

**Closed by Kithan87** 2020-03-23 23:28 UTC
Labels: duplicate
