### ISSUE TITLE
[Anon] Bug report: Vampire Counts - 8thBRB_8thAB.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/whfb#218] opened 2017-02-06 21:10 UTC
**File:** Vampire Counts - 8thBRB_8thAB.catz

**BattleScribe version:** 2.00.24

**Platform:** Android

**Dropbox:** No

**Description:** Hi, when I create a new Vampire Counts roster, I always get the error "Special must have 1 more selections of Corpse Cart (minimum 1)." Even when I don't have a Corpse Cart selected...

Thanks for helping and let me thank you again for the app and the data!

**Comment by Kithan87** [comment] 2020-02-25 00:16
Closing as unable to reproduce in v6 of Vampire Counts file and BS v2.03.12

**Closed by Kithan87** 2020-02-25 00:16 UTC
Labels: unable to replicate
