### ISSUE TITLE
[Anon] Bug report: Vampire Counts - 8thBRB_8thAB.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/whfb#222] opened 2017-03-08 21:28 UTC
**File:** Vampire Counts - 8thBRB_8thAB.catz

**BattleScribe version:** 2.00.18

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Error report: special must have 1 or more selections from Corpse Cart. This is not required for a standard or End Times list. This needs to be removed.

**Comment by Kithan87** [comment] 2020-02-24 20:49
Closing, duplicate of #218

**Closed by Kithan87** 2020-02-24 20:49 UTC
Labels: duplicate
